### PR TITLE
allright this time saner

### PR DESCRIPTION
**Pull request by lichtkind**
in preperation for inverted method and the gauss seidel i would like to add an add method to Row class, is that allright?

cheers

### CODE REVIEW

**Comment by lichtkind** [comment]
hang on i fix this :)

**Comment by pierre-vigier** [comment]
i'm travelling those days, i'll check that once done (in 2/3 days), Thanks
for all

**Comment by lichtkind** [comment]
gooo,

yey im done :)


no my endgoal for now is to get the inverse, and eigenvalues, and spectral radius, maybe also other norms and maybe condition

**Comment by pierre-vigier** [comment]
I was planning to add LU decomposition after as well, but thanks for all those additions

**Comment by lichtkind** [comment]
actually i have to do LU for next exam and also cholesky , seidel and a bunch

**Comment by pierre-vigier** [comment]
To be honest, my main problem here is that my last mathematic lesson with Matrix was in 2003, and i forgot a lot, but interesting to check that again

**Comment by lichtkind** [comment]
allright but today i go for inverse and rank will be a stop on the way, where can we draft the API guidelines (mail) i want to be also close as sanely possible on mahematica/octave, since thats what people are used to

**Pull request merged**
