### PR TITLE
add to "math" category in index

### PR DESCRIPTION
**Pull request by lichtkind**
im back hope we can chat somewhere

### CODE REVIEW

**Comment by lichtkind** [comment]
travis has to be fixed, my patch is meta text only

**Comment by lichtkind** [comment]
allright test are now good except one dubious

**Comment by lichtkind** [comment]
please tell me how i can reach yo for communication im prepared to do some work again

**Comment by lichtkind** [comment]
i will split it

**Comment by pierre-vigier** [comment]
Sorry, i was pretty busy, i should be able to give you commit right on master there

**Pull request closed without merging**
